name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        - name: Create an issue
  uses: JasonEtco/create-an-issue@v1.2.0
  job_id:
   - name: GraphQL query
  uses: helaili/github-graphql-action@1.0
  job_id:
      234 
